import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
/** @jsxImportSource theme-ui */ 
import { ThemeProvider, Container } from 'theme-ui'
import  theme  from '../theme.js'
import AppBody from '@/components/AppBody.js'
import FlagGrid from '@/components/FlagGrid.js'

import { Provider } from 'react-redux'


export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <AppBody>
      <main className={styles.main}>
        <FlagGrid></FlagGrid>
      </main>
     </AppBody>
     </Container>
  )
}
