import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
/** @jsxImportSource theme-ui */ 
import { ThemeProvider, Container } from 'theme-ui'
import  theme  from '../theme.js'
import AppBody from '@/components/AppBody.js'
import FlagGrid from '@/components/FlagGrid.js'
import { Poiret_One } from "@next/font/google";
import { Provider } from 'react-redux'

const poiret_one = Poiret_One({weight: "400", subsets: ["latin"]} )
export default function Home() {
  return (
    <Container className={poiret_one.className}>
      <Head>
        <title>Learn Flagmojis!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        <link rel="manifest" href="/site.webmanifest"></link>
      </Head>
    <AppBody>
      <main className={styles.main}>
        <FlagGrid></FlagGrid>
      </main>
     </AppBody>
     </Container>
  )
}
